name: ai-pai-build

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/flyljx/ai-pai-web:latest
  admin:
    build:
      context: .
      dockerfile: Dockerfile.admin
    image: ghcr.io/flyljx/ai-pai-admin:latest
  api:
    build:
      context: ./go-server
      dockerfile: Dockerfile
    image: ghcr.io/flyljx/ai-pai-api:latest
